const allTags = [
    "Athletic Club",
    "Atlético de Madrid",
    "Balón de oro",
    "Borussia Dortmund",
    "Bundesliga",
    "Celta de Vigo",
    "Champions League",
    "Competiciones Europeas",
    "Competiciones Internacionales",
    "Conference League",
    "Copa América",
    "Copa del rey",
    "Elche CF",
    "Eurocopa",
    "Europa League",
    "FC Barcelona",
    "Fútbol Internacional",
    "Fútbol Nacional",
    "Getafe CF",
    "Girona",
    "Historia de los Mundiales",
    "Iñaki Williams",
    "LaLiga",
    "LaLiga EA Sports",
    "LaLiga Hypermotion",
    "Levante",
    "Ligas Europeas",
    "Ligue 1",
    "MLS",
    "Mundial de Clubes",
    "Mundial Qatar 2022",
    "Mundial Uruguay 1930",
    "Nations League",
    "Neymar Jr",
    "Osasuna",
    "Otros equipos",
    "Premier League",
    "Primeira Liga de Portugal",
    "Primera RFEF",
    "PSG",
    "Rafa Benítez",
    "RCD Espanyol",
    "RCD Mallorca",
    "Real Betis",
    "Real Madrid",
    "Real Sociedad",
    "Repescas Mundial Qatar 2022",
    "Segunda RFEF",
    "Selección Española",
    "Serie A",
    "Sevilla FC",
    "Sorteo Mundial Qatar 2022",
    "Tercera RFEF",
    "Valencia CF",
]

export default allTags